version: 2
executorType: machine
stages:
  build:
    workDir: /var/www/html
    steps:
      - type: shell
        name: Install Project Dependencies
        command: pip install -U pytest
      - type: shell
        name: Run Tests
        command: |
          pytest test_circleci.py --junitxml=test1.xml
          cat test1.xml
      - type: artifacts-store
        path: build/tests/phpspec
        destination: phpspec
      - type: test-results-store
        path: build/tests
