version: 2
executorType: machine
stages:
  build:
    workDir: .
    steps:
      - type: shell
        name: Install Project Dependencies
        command: pip install -U pytest
      - type: shell
        name: Run Tests
        command: |
          mkdir -p ./build/
          pytest test_circleci.py --junitxml=build/test1.xml
          cat build/test1.xml
      - type: artifacts-store
        path: build/tests/phpspec
        destination: phpspec
      - type: test-results-store
        path: build/tests
