version: 2
executorType: docker
stages:
  build:
    workDir: .
    steps:
      - type: checkout
      - type: shell
        name: Install Project Dependencies
        command: pip install -U pytest
      - type: shell
        name: Run Tests
        command: |
          mkdir -p build/tests/phpspec
          pytest test_circleci.py --junitxml=junit/test1.xml
          cat build/tests/phpspec/test1.xml
      - type: artifacts-store
        path: build/tests/phpspec
        destination: phpspec
      - type: test-results-store
        path: build/tests
